sonar.projectKey=petfinder-saas
sonar.projectName=EcoSistemPet
sonar.sourceEncoding=UTF-8
sonar.sources=app,public,config
sonar.tests=tests
sonar.exclusions=vendor/**,uploads/**,storage/**,release/**,node_modules/**
sonar.test.inclusions=tests/**/*.php
